// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import FileUploadController from "controllers/file_upload_controller"
application.register("file-upload", FileUploadController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PasswordVisibilityController from "controllers/password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import SidebarController from "controllers/sidebar_controller"
application.register("sidebar", SidebarController)

import ToastController from "controllers/toast_controller"
application.register("toast", ToastController)
