// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import FileUploadController from "controllers/file_upload_controller"
application.register("file-upload", FileUploadController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PasswordVisibilityController from "controllers/password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import SidebarController from "controllers/sidebar_controller"
application.register("sidebar", SidebarController)

import ToastController from "controllers/toast_controller"
application.register("toast", ToastController)

import OrderPricingController from "controllers/order_pricing_controller"
application.register("order-pricing", OrderPricingController)

import DynamicAttendeesController from "controllers/dynamic_attendees_controller"
application.register("dynamic-attendees", DynamicAttendeesController)

import PaymentProviderController from "controllers/payment_provider_controller"
application.register("payment-provider", PaymentProviderController)

import LocalTimeController from "controllers/local_time_controller"
application.register("local-time", LocalTimeController)

import TabsController from "controllers/tabs_controller"
application.register("tabs", TabsController)

import UpgradeCalculatorController from "controllers/upgrade_calculator_controller"
application.register("upgrade-calculator", UpgradeCalculatorController)
