<%
  require "dotenv"
  Dotenv.load
%>
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

default: &default
  adapter: postgresql
  encoding: unicode
  # Bump pool size slightly because Solid Queue needs its own connections
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>

development:
  <<: *default
  database: arc_events_development

test:
  <<: *default
  database: arc_events_test

production:
  primary: &primary_production
    <<: *default
    database: arc_events_production

  # Point Cache to the SAME database, but keep the migration path
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate

  # Point Queue to the SAME database
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate

  # Point Cable to the SAME database
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
